/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYardRouteImport } from './routes/_authenticated/yard'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTomorrowRouteImport } from './routes/_authenticated/tomorrow'
import { Route as AuthenticatedTendersRouteImport } from './routes/_authenticated/tenders'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated/stores'
import { Route as AuthenticatedShipmentsRouteImport } from './routes/_authenticated/shipments'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedRatesRouteImport } from './routes/_authenticated/rates'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLoadsRouteImport } from './routes/_authenticated/loads'
import { Route as AuthenticatedKioskRouteImport } from './routes/_authenticated/kiosk'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedExceptionsRouteImport } from './routes/_authenticated/exceptions'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContainersRouteImport } from './routes/_authenticated/containers'
import { Route as AuthenticatedCarriersRouteImport } from './routes/_authenticated/carriers'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedHistoryIndexRouteImport } from './routes/_authenticated/history.index'
import { Route as ApiPublicTrackingRouteImport } from './routes/api/public/tracking'
import { Route as ApiPublicSheetDrainRouteImport } from './routes/api/public/sheet-drain'
import { Route as ApiPublicReadyRouteImport } from './routes/api/public/ready'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedHistoryLoadIdRouteImport } from './routes/_authenticated/history.$loadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYardRoute = AuthenticatedYardRouteImport.update({
  id: '/yard',
  path: '/yard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTomorrowRoute = AuthenticatedTomorrowRouteImport.update({
  id: '/tomorrow',
  path: '/tomorrow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTendersRoute = AuthenticatedTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShipmentsRoute = AuthenticatedShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRatesRoute = AuthenticatedRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoadsRoute = AuthenticatedLoadsRouteImport.update({
  id: '/loads',
  path: '/loads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKioskRoute = AuthenticatedKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExceptionsRoute = AuthenticatedExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContainersRoute = AuthenticatedContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarriersRoute = AuthenticatedCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryIndexRoute =
  AuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTrackingRoute = ApiPublicTrackingRouteImport.update({
  id: '/api/public/tracking',
  path: '/api/public/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSheetDrainRoute = ApiPublicSheetDrainRouteImport.update({
  id: '/api/public/sheet-drain',
  path: '/api/public/sheet-drain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReadyRoute = ApiPublicReadyRouteImport.update({
  id: '/api/public/ready',
  path: '/api/public/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryLoadIdRoute =
  AuthenticatedHistoryLoadIdRouteImport.update({
    id: '/history/$loadId',
    path: '/history/$loadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/carriers': typeof AuthenticatedCarriersRoute
  '/containers': typeof AuthenticatedContainersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/exceptions': typeof AuthenticatedExceptionsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/kiosk': typeof AuthenticatedKioskRoute
  '/loads': typeof AuthenticatedLoadsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/tenders': typeof AuthenticatedTendersRoute
  '/tomorrow': typeof AuthenticatedTomorrowRoute
  '/users': typeof AuthenticatedUsersRoute
  '/yard': typeof AuthenticatedYardRoute
  '/history/$loadId': typeof AuthenticatedHistoryLoadIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/api/public/sheet-drain': typeof ApiPublicSheetDrainRoute
  '/api/public/tracking': typeof ApiPublicTrackingRoute
  '/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/carriers': typeof AuthenticatedCarriersRoute
  '/containers': typeof AuthenticatedContainersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/exceptions': typeof AuthenticatedExceptionsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/kiosk': typeof AuthenticatedKioskRoute
  '/loads': typeof AuthenticatedLoadsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/rates': typeof AuthenticatedRatesRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/tenders': typeof AuthenticatedTendersRoute
  '/tomorrow': typeof AuthenticatedTomorrowRoute
  '/users': typeof AuthenticatedUsersRoute
  '/yard': typeof AuthenticatedYardRoute
  '/history/$loadId': typeof AuthenticatedHistoryLoadIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/api/public/sheet-drain': typeof ApiPublicSheetDrainRoute
  '/api/public/tracking': typeof ApiPublicTrackingRoute
  '/history': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/carriers': typeof AuthenticatedCarriersRoute
  '/_authenticated/containers': typeof AuthenticatedContainersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/exceptions': typeof AuthenticatedExceptionsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/kiosk': typeof AuthenticatedKioskRoute
  '/_authenticated/loads': typeof AuthenticatedLoadsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/rates': typeof AuthenticatedRatesRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shipments': typeof AuthenticatedShipmentsRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRoute
  '/_authenticated/tenders': typeof AuthenticatedTendersRoute
  '/_authenticated/tomorrow': typeof AuthenticatedTomorrowRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/yard': typeof AuthenticatedYardRoute
  '/_authenticated/history/$loadId': typeof AuthenticatedHistoryLoadIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/api/public/sheet-drain': typeof ApiPublicSheetDrainRoute
  '/api/public/tracking': typeof ApiPublicTrackingRoute
  '/_authenticated/history/': typeof AuthenticatedHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/billing'
    | '/carriers'
    | '/containers'
    | '/dashboard'
    | '/driver'
    | '/drivers'
    | '/exceptions'
    | '/integrations'
    | '/kiosk'
    | '/loads'
    | '/onboarding'
    | '/orders'
    | '/planning'
    | '/rates'
    | '/reconciliation'
    | '/reports'
    | '/search'
    | '/settings'
    | '/shipments'
    | '/stores'
    | '/tenders'
    | '/tomorrow'
    | '/users'
    | '/yard'
    | '/history/$loadId'
    | '/api/public/health'
    | '/api/public/ready'
    | '/api/public/sheet-drain'
    | '/api/public/tracking'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/carriers'
    | '/containers'
    | '/dashboard'
    | '/driver'
    | '/drivers'
    | '/exceptions'
    | '/integrations'
    | '/kiosk'
    | '/loads'
    | '/onboarding'
    | '/orders'
    | '/planning'
    | '/rates'
    | '/reconciliation'
    | '/reports'
    | '/search'
    | '/settings'
    | '/shipments'
    | '/stores'
    | '/tenders'
    | '/tomorrow'
    | '/users'
    | '/yard'
    | '/history/$loadId'
    | '/api/public/health'
    | '/api/public/ready'
    | '/api/public/sheet-drain'
    | '/api/public/tracking'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/billing'
    | '/_authenticated/carriers'
    | '/_authenticated/containers'
    | '/_authenticated/dashboard'
    | '/_authenticated/driver'
    | '/_authenticated/drivers'
    | '/_authenticated/exceptions'
    | '/_authenticated/integrations'
    | '/_authenticated/kiosk'
    | '/_authenticated/loads'
    | '/_authenticated/onboarding'
    | '/_authenticated/orders'
    | '/_authenticated/planning'
    | '/_authenticated/rates'
    | '/_authenticated/reconciliation'
    | '/_authenticated/reports'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/shipments'
    | '/_authenticated/stores'
    | '/_authenticated/tenders'
    | '/_authenticated/tomorrow'
    | '/_authenticated/users'
    | '/_authenticated/yard'
    | '/_authenticated/history/$loadId'
    | '/api/public/health'
    | '/api/public/ready'
    | '/api/public/sheet-drain'
    | '/api/public/tracking'
    | '/_authenticated/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicReadyRoute: typeof ApiPublicReadyRoute
  ApiPublicSheetDrainRoute: typeof ApiPublicSheetDrainRoute
  ApiPublicTrackingRoute: typeof ApiPublicTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/yard': {
      id: '/_authenticated/yard'
      path: '/yard'
      fullPath: '/yard'
      preLoaderRoute: typeof AuthenticatedYardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tomorrow': {
      id: '/_authenticated/tomorrow'
      path: '/tomorrow'
      fullPath: '/tomorrow'
      preLoaderRoute: typeof AuthenticatedTomorrowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenders': {
      id: '/_authenticated/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof AuthenticatedTendersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipments': {
      id: '/_authenticated/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AuthenticatedShipmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rates': {
      id: '/_authenticated/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AuthenticatedRatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loads': {
      id: '/_authenticated/loads'
      path: '/loads'
      fullPath: '/loads'
      preLoaderRoute: typeof AuthenticatedLoadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kiosk': {
      id: '/_authenticated/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof AuthenticatedKioskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exceptions': {
      id: '/_authenticated/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof AuthenticatedExceptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/containers': {
      id: '/_authenticated/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof AuthenticatedContainersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carriers': {
      id: '/_authenticated/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof AuthenticatedCarriersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history/': {
      id: '/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AuthenticatedHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/tracking': {
      id: '/api/public/tracking'
      path: '/api/public/tracking'
      fullPath: '/api/public/tracking'
      preLoaderRoute: typeof ApiPublicTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sheet-drain': {
      id: '/api/public/sheet-drain'
      path: '/api/public/sheet-drain'
      fullPath: '/api/public/sheet-drain'
      preLoaderRoute: typeof ApiPublicSheetDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ready': {
      id: '/api/public/ready'
      path: '/api/public/ready'
      fullPath: '/api/public/ready'
      preLoaderRoute: typeof ApiPublicReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history/$loadId': {
      id: '/_authenticated/history/$loadId'
      path: '/history/$loadId'
      fullPath: '/history/$loadId'
      preLoaderRoute: typeof AuthenticatedHistoryLoadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCarriersRoute: typeof AuthenticatedCarriersRoute
  AuthenticatedContainersRoute: typeof AuthenticatedContainersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedExceptionsRoute: typeof AuthenticatedExceptionsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedKioskRoute: typeof AuthenticatedKioskRoute
  AuthenticatedLoadsRoute: typeof AuthenticatedLoadsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedRatesRoute: typeof AuthenticatedRatesRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShipmentsRoute: typeof AuthenticatedShipmentsRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRoute
  AuthenticatedTendersRoute: typeof AuthenticatedTendersRoute
  AuthenticatedTomorrowRoute: typeof AuthenticatedTomorrowRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedYardRoute: typeof AuthenticatedYardRoute
  AuthenticatedHistoryLoadIdRoute: typeof AuthenticatedHistoryLoadIdRoute
  AuthenticatedHistoryIndexRoute: typeof AuthenticatedHistoryIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCarriersRoute: AuthenticatedCarriersRoute,
  AuthenticatedContainersRoute: AuthenticatedContainersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedExceptionsRoute: AuthenticatedExceptionsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedKioskRoute: AuthenticatedKioskRoute,
  AuthenticatedLoadsRoute: AuthenticatedLoadsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedRatesRoute: AuthenticatedRatesRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShipmentsRoute: AuthenticatedShipmentsRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRoute,
  AuthenticatedTendersRoute: AuthenticatedTendersRoute,
  AuthenticatedTomorrowRoute: AuthenticatedTomorrowRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedYardRoute: AuthenticatedYardRoute,
  AuthenticatedHistoryLoadIdRoute: AuthenticatedHistoryLoadIdRoute,
  AuthenticatedHistoryIndexRoute: AuthenticatedHistoryIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicReadyRoute: ApiPublicReadyRoute,
  ApiPublicSheetDrainRoute: ApiPublicSheetDrainRoute,
  ApiPublicTrackingRoute: ApiPublicTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
